version: '3'
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3127:3127
    volumes:
    - ./front/app:/app/app
  
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 5127:5127
    env_file:
      - .env
    volumes:
      - ./back:/app
