version: '3'
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
    - ./front:/app
  
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ./back:/app
